version: '3.8'

services:
    db:
        build: ./postgre
        env_file:
            - ./postgre/.env
        ports:
            - "5432:5432"
        volumes:
            - ./postgre/res/data/:/var/lib/postgresql/data

    conback:
        build: ./spring/wb
        ports:
            - "8080:8080"
        volumes:
            - ./spring/wb:/srv/docker-server
